# Basic Site Settings
locale                   : "en-UK"
title                    : "Frazer N. Forrester"
title_separator          : "-"
name                     : &name "Frazer N. Forrester"
description              : &description "Computational Chemist at Newcastle University"
tagline                  : "Computational Chemistry · Solid-State Ionics · Energy Materials"
url                      : "https://www.frazerforrester.com"
baseurl                  : ""
repository               : "fforrester/fforrester.github.io"

# Author Profile
author:
  name             : "Frazer N. Forrester"
  avatar           : "pp.JPG"
  bio              : "Computational Chemist at Newcastle University"
  location         : "Newcastle, UK"
  employer         : "Newcastle University"
  email            : "f.forrester2@newcastle.ac.uk"
  github           : "fforrester"
  linkedin         : "frazerforrester"
  orcid            : "https://orcid.org/0000-0002-5340-3925"
  googlescholar    : "https://scholar.google.com/citations?user=MqDJwsEAAAAJ"
  twitter          : "frazerforrester"
  goodreads        : "frazerforrester"
  instagram        : "frazerforrester"
  pinterest        : "frazerforrester"
  facebook         : "frazer.forrester"
  tumblr           : "frazerforrester"

# Controls which author links appear in the "Other" dropdown
secondary_links:
  - goodreads
  - instagram
  - pinterest
  - facebook
  - tumblr

# SEO Related
google_site_verification : iYVfI-7vesU9FW_Sd3P_Ymcsb5IZ9Xty0bQ7AAo3IqI
bing_site_verification   :
yandex_site_verification :

# Social Sharing
twitter:
  username               : frazerforrester
facebook:
  username               : frazer.forrester
  app_id                 :
  publisher              :
og_image                 :

# Structured Data
social:
  type                   : "Person"
  name                   : "Frazer N. Forrester"
  links:
    - https://github.com/fforrester
    - https://www.linkedin.com/in/frazerforrester
    - https://orcid.org/0000-0002-5340-3925
    - https://scholar.google.com/citations?user=MqDJwsEAAAAJ
    - https://twitter.com/frazerforrester

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          :  # Add your Google Analytics ID if needed

# Output Settings
permalink                : /:categories/:title/
timezone                 : Europe/London

# Theme Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Feeds
atom_feed:
  path                   :

# Jekyll Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Markdown & Sass
markdown                 : kramdown
highlighter              : rouge
kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
sass:
  sass_dir: _sass
  style: compressed

# Output Control
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-*"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Gemfile*
  - LICENSE
  - README
  - node_modules
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: "\n\n"
incremental: false

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Archives (optional)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
